import { RFPercentage } from 'react-native-responsive-fontsize'
export const size = {
  huge: RFPercentage(4.5),
  xxxtitle: RFPercentage(3.8),
  xxtitle: RFPercentage(3.6),
  xtitle: RFPercentage(3.4),
  title: RFPercentage(3.2),
  h1: RFPercentage(3.0),
  h2: RFPercentage(2.8),
  h3: RFPercentage(2.6),
  h4: RFPercentage(2.5),
  h5: RFPercentage(2.4),
  h6: RFPercentage(2.2),
  xxlarge: RFPercentage(2.0),
  xlarge: RFPercentage(1.9),
  large: RFPercentage(1.8),
  medium: RFPercentage(1.7),
  normal: RFPercentage(1.6),
  small: RFPercentage(1.5),
  xsmall: RFPercentage(1.4),
  xxsmall: RFPercentage(1.3),
  tiny: RFPercentage(1.2),
  xtiny: RFPercentage(1.1),
  xxtiny: RFPercentage(1.0),
  xxxtiny: RFPercentage(0.9),
};
// export const size = {
//   huge: 50,
//   xxxtitle: 38,
//   xxtitle: 36,
//   xtitle: 34,
//   title: 32,
//   h1: 30,
//   h2: 28,
//   h3: 26,
//   h4: 25,
//   h5: 24,
//   h6: 22,
//   xxlarge: 20,
//   xlarge: 19,
//   large: 18,
//   medium: 17,
//   normal: 16,
//   small: 15,
//   xsmall: 14,
//   xxsmall: 13,
//   tiny: 12,
//   xtiny: 11,
//   xxtiny: 10,
//   xxxtiny: 9,
// };

export const family = {
  SP_Regular: 'SofiaProRegular',
  SP_Medium: 'SofiaProMedium',
  SP_BlackItalic: 'SofiaProBlack-Italic',
  SP_SemiBold: 'SofiaProSemiBold',
  SP_SemiBold_Italic: 'SofiaProSemiBold-Italic',
  SP_Bold: 'SofiaProBold',
};